# Generated by Django 3.0.2 on 2021-08-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210818_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikesModel',
        ),
    ]
